import { HttpClient } from '@angular/common/http';
import { inject } from '@angular/core';

import { forkJoin, map, Observable, of, switchMap, tap } from 'rxjs';
import z from 'zod';

import { environment } from '@environment';

import { DataHelper } from '../helpers';
import { ExcelDatasetModel, ExcelHelper, ExcelLabelModel } from '../helpers/excel';
import {
  ExportRequestModel,
  PagingDataModel,
  PagingRequestModel,
  PagingResponseModel,
  ResponseModel,
} from '../models';
import { BaseAPIOperator } from './operators';

/**
 * Base API Service
 */
export class BaseApiService<T = any> {
  protected _baseUrl = environment.apiUrl;
  protected _http = inject(HttpClient);

  protected _schema!: z.ZodSchema<T>;
  protected _schemaDetail: z.ZodSchema<T> = this._schema;
  protected _cacheMap = new Map<string, any>();

  // -----------------------------------------------------------------------------------------------------
  // @ Public methods
  // -----------------------------------------------------------------------------------------------------

  clearCache() {
    this._cacheMap.clear();
  }

  // -----------------------------------------------------------------------------------------------------
  // @ Protected methods
  // -----------------------------------------------------------------------------------------------------

  /**
   * @description List all items
   * @returns Observable<T[]> array of items
   */
  protected _list(): Observable<T[]> {
    if (this._cacheMap.has(this._baseUrl)) {
      return of(this._cacheMap.get(this._baseUrl));
    }

    return this._http.get<ResponseModel<T[]>>(this._baseUrl).pipe(
      BaseAPIOperator.responseHandler(),
      map((list) => {
        if (this._schema) {
          return (list || []).map((item) => this._schema.parse(item));
        }

        return list || [];
      }),
      tap((data) => {
        this._cacheMap.set(this._baseUrl, data);
      })
    );
  }

  /**
   * @description List all items with pagination
   * @param page page index 1-based
   * @param size number of items per page
   * @returns Observable<PagingDataModel<T>> array of items with pagination
   */
  protected _paginate(options: PagingRequestModel): Observable<PagingDataModel<T>> {
    const params = DataHelper.toSearchParams(options);

    return this._http
      .get<PagingResponseModel<T>>(`${this._baseUrl}?${params.toString()}`)
      .pipe(BaseAPIOperator.responseHandler(), BaseAPIOperator.pagingHandler(this._schema));
  }

  /**
   * @description Retrieve all items by using forkJoin to combine data from multiple paginated API requests
   * @param chunkSize The number of items to fetch per page in each API request
   * @return Observable<T[]> all items
   */
  protected _all(options: ExportRequestModel & Partial<PagingRequestModel>): Observable<T[]> {
    const chunkSize = options?.chunkSize || 100;

    return this._paginate({
      ...options,
      page: 1,
      pageSize: chunkSize,
    }).pipe(
      switchMap((response) => {
        if ((response?.totalPages || 0) <= 1) {
          return of(response?.list || []);
        }

        const requests: Observable<T[]>[] = [];
        for (let page = 2; page <= (response?.totalPages || 0); page++) {
          requests.push(
            this._paginate({ ...options, page: page, pageSize: chunkSize }).pipe(
              map((res) => res?.list || [])
            )
          );
        }

        return forkJoin(requests).pipe(
          map((pages) => [...(response?.list || []), ...pages.flat()])
        );
      })
    );
  }

  /**
   * @description Read an item by id
   * @param id guid of item
   * @returns Observable<T> full item model
   */
  protected _read(id: string): Observable<T> {
    return this._http
      .get<ResponseModel<T>>(`${this._baseUrl}/${id}`)
      .pipe(BaseAPIOperator.responseHandler<T>(this._schemaDetail));
  }

  /**
   * @description Create an item
   * @param data item model
   * @returns Observable<T> item model with guid generated by server
   */
  protected _create(data: Partial<T | any>): Observable<string> {
    return this._http.post<ResponseModel<string>>(this._baseUrl, data).pipe(
      BaseAPIOperator.responseHandler(),
      tap(() => this._cacheMap.clear())
    );
  }

  /**
   * @description Update full item
   * @param id guid of item
   * @param data full item model
   * @returns Observable<T> item model that updated
   */
  protected _update(id: string, data: Partial<T>): Observable<boolean> {
    return this._http.put<ResponseModel<boolean>>(`${this._baseUrl}/${id}`, data).pipe(
      BaseAPIOperator.responseHandler(),
      tap(() => this._cacheMap.clear())
    );
  }

  /**
   * @description Update partial item
   * @param id guid of item
   * @param data partial item model
   * @returns Observable<T> item model that updated
   */
  protected _patch(id: string, data: Partial<T | any>): Observable<boolean> {
    return this._http
      .patch<ResponseModel<boolean>>(`${this._baseUrl}/${id}`, DataHelper.toJsonPatch(data))
      .pipe(
        BaseAPIOperator.responseHandler(),
        tap(() => this._cacheMap.clear())
      );
  }

  /**
   * @description Delete an item
   * @param id guid of item
   * @returns Observable<T> boolean value
   */
  protected _delete(id: string): Observable<boolean> {
    return this._http.delete<ResponseModel<boolean>>(`${this._baseUrl}/${id}`).pipe(
      BaseAPIOperator.responseHandler(),
      tap(() => this._cacheMap.clear())
    );
  }

  /**
   * @description Export all data to excel format
   * @param excelLabels
   * @param excelOptions
   * @returns Excel workbook
   */
  protected _export(
    excelLabels: ExcelLabelModel[],
    filterOptions: ExportRequestModel & Partial<PagingRequestModel>
  ) {
    return this._all(filterOptions).pipe(
      map((res) => {
        const workbook = ExcelHelper.createWorkbook();
        const worksheet = workbook.addWorksheet('Sheet1');

        const datasets: ExcelDatasetModel[] = res.map((item) =>
          ExcelHelper.pickFields(
            item as Record<string, any>,
            excelLabels.map((l) => l.key)
          )
        );

        ExcelHelper.table(worksheet, excelLabels, datasets);

        return workbook;
      })
    );
  }
}
