declare const fadeIn: import("@angular/animations").AnimationTriggerMetadata;
declare const fadeInTop: import("@angular/animations").AnimationTriggerMetadata;
declare const fadeInBottom: import("@angular/animations").AnimationTriggerMetadata;
declare const fadeInLeft: import("@angular/animations").AnimationTriggerMetadata;
declare const fadeInRight: import("@angular/animations").AnimationTriggerMetadata;
declare const fadeOut: import("@angular/animations").AnimationTriggerMetadata;
declare const fadeOutTop: import("@angular/animations").AnimationTriggerMetadata;
declare const fadeOutBottom: import("@angular/animations").AnimationTriggerMetadata;
declare const fadeOutLeft: import("@angular/animations").AnimationTriggerMetadata;
declare const fadeOutRight: import("@angular/animations").AnimationTriggerMetadata;
export { fadeIn, fadeInBottom, fadeInLeft, fadeInRight, fadeInTop, fadeOut, fadeOutBottom, fadeOutLeft, fadeOutRight, fadeOutTop, };
