import { BooleanInput } from '@angular/cdk/coercion';
import { ChangeDetectorRef, OnDestroy, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { NavigationItem } from '../../../navigation.types';
import { NavigationService } from '../../../navigation.service';
import * as i0 from "@angular/core";
export declare class VerticalNavigationCollapsableItemComponent implements OnInit, OnDestroy {
    private _router;
    private _changeDetectorRef;
    private _navigationService;
    static ngAcceptInputType_autoCollapse: BooleanInput;
    autoCollapse: boolean;
    item: NavigationItem;
    name: string;
    isCollapsed: boolean;
    isExpanded: boolean;
    private _verticalNavigationComponent;
    private _unsubscribeAll;
    constructor(_router: Router, _changeDetectorRef: ChangeDetectorRef, _navigationService: NavigationService);
    get classList(): any;
    ngOnInit(): void;
    ngOnDestroy(): void;
    collapse(): void;
    expand(): void;
    toggleCollapsable(): void;
    trackByFn(index: number, item: any): any;
    private _hasActiveChild;
    private _isChildrenOf;
    static ɵfac: i0.ɵɵFactoryDeclaration<VerticalNavigationCollapsableItemComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<VerticalNavigationCollapsableItemComponent, "vertical-navigation-collapsable-item", never, { "autoCollapse": { "alias": "autoCollapse"; "required": false; }; "item": { "alias": "item"; "required": false; }; "name": { "alias": "name"; "required": false; }; }, {}, never, never, true, never>;
}
